name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: |
        docker build -t compound-interest-calculator:latest .
    
    - name: Test Docker image
      run: |
        docker run -d -p 5000:5000 --name test-container compound-interest-calculator:latest
        # Wait for container to start
        sleep 5
        # Test if container is running
        docker ps | grep test-container
        # Check if the application is responsive
        curl -s http://localhost:5000/ | grep "Compound Interest Calculator"
        # Cleanup
        docker stop test-container
        docker rm test-container